# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'CryptEx-Back: Build - Test - Deploy'

on:
  push:
    branches: [ master ]
    paths: [ "src/back-end/**", ".github/workflows/backend.yml" ]

env:
  app_name: 'Cryptex-Back'

jobs:
  build:
    name: .NET Back-End CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/back-end/CryptEx/

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    
    - name:
      run: dotnet restore
    
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --verbosity normal
    
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
      
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app_name }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_abb347b9b08c4551b383815c8cff1a24 }}
        package: ${{env.DOTNET_ROOT}}/myapp
